traffic_configs:
  default:
    start_date: "2024-08-01"
    end_date: "2024-08-08"
    policy_decisions:
      - allowed
      - potentially_blocked
    max_results: 100000

  example:
    start_date: "2024-08-01"
    end_date: "2024-08-08"
    include_sources:
      - "env=dev"
    exclude_sources:
      - "app=assetmgmt"
    include_destinations:
      - "env=prod"
    exclude_destinations: []
    policy_decisions:
      - allowed
      - potentially_blocked
    max_results: 100000


